# Generated by Django 3.2.23 on 2023-12-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
