# Generated by Django 3.2.23 on 2023-12-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_customuser_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='booked_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='booked_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
