# Generated by Django 3.2.23 on 2023-12-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20231207_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
