# Generated by Django 3.2.23 on 2023-12-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_table_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
