# Generated by Django 3.2.23 on 2023-12-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_table_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_membership_approved',
            field=models.BooleanField(default=False),
        ),
    ]
