# Generated by Django 3.2.23 on 2023-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_customuser_is_membership_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_end_time',
            field=models.TimeField(null=True),
        ),
    ]
